export const WITHDRAW_POST_STARTED		='WITHDRAW_POST_STARTED';
export const WITHDRAW_POST_FINISHED		='WITHDRAW_POST_FINISHED';
export const WITHDRAW_POST_ERROR		='WITHDRAW_POST_ERROR';

export const MIN_FEE_GET_STARTED		='MIN_FEE_GET_STARTED';
export const MIN_FEE_GET_FINISHED		='MIN_FEE_GET_FINISHED';
export const MIN_FEE_GET_ERROR			='MIN_FEE_GET_ERROR';
