export const BALANCE_GET_STARTED	='BALANCE_GET_STARTED';
export const BALANCE_GET_FINISHED	='BALANCE_GET_FINISHED';
export const BALANCE_GET_ERROR		='BALANCE_GET_ERROR';

export const BALANCE_WS_STARTED		='BALANCE_WS_STARTED';
export const BALANCE_WS_PARTIAL		='BALANCE_WS_PARTIAL';
export const BALANCE_WS_UPDATE		='BALANCE_WS_UPDATE';
export const BALANCE_WS_DELETE		='BALANCE_WS_DELETE';
export const BALANCE_WS_INSERT		='BALANCE_WS_INSERT';
export const BALANCE_WS_ERROR		='BALANCE_WS_ERROR';
