export const UPDATE_SETTINGS		='UPDATE_SETTINGS';
export const SET_DEADMAN_INTERVAL	='SET_DEADMAN_INTERVAL';
export const CLEAR_DEADMAN_INTERVAL ='CLEAR_DEADMAN_INTERVAL';
export const SET_VALID_AUTH			='SET_VALID_AUTH';
export const START_VALID_AUTH		='START_VALID_AUTH';
export const SET_VALID_ERROR		='SET_VALID_ERROR';