version: 2.1
jobs:
  ios:
    macos:
      xcode: "11.4"
    working_directory: ~/goliquid-app

    # use a --login shell so our "set Ruby version" command gets picked up for later steps
    shell: /bin/bash --login -o pipefail

    steps:
      - checkout
      - run:
          name: cloning private repo of distribution cert
          command: git clone git@github.com:evilqubit/Fastlane-SharedKeys.git ~/Library/GoLiquid-certs/
      - run:
          name: copy certs to app folder
          command: rsync -av --exclude=".*" ~/Library/GoLiquid-certs/ ~/goliquid-app/ios/builds/

      - run:
          name: create new keychain
          command: |
            security create-keychain -p "" temporary.keychain
            security default-keychain -s temporary.keychain
            security unlock-keychain -p "" temporary.keychain
            security set-keychain-settings -lut 7200 temporary.keychain

      - run:
          name: install copied certs
          command: security import ~/goliquid-app/ios/builds/H83CWZN6X5.p12 -t agg -k temporary.keychain -P "" -A

      - run:
          name: print code signing credentials status 
          command: security find-identity -v -p codesigning
      
      - run:
          name: set Ruby version
          command:  echo "ruby-2.4" > ~/.ruby-version

      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: npm install

      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}-{{ arch }}
          paths:
            - ~/.cache/npm

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - restore_cache:
          key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}

      - run:
          command: bundle install
          working_directory: ios

      - save_cache:
          key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle

      - run:
          command: bundle exec fastlane beta
          working_directory: ios

workflows:
  version: 2
  ios:
    jobs:
      - ios