# .circleci/config.yml
version: 2.1
jobs:
  testflight:
    macos:
      xcode: 11.4.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: testflight
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output

workflows:
  testflight:
    jobs:
      - testflight