export const POSITION_GET_STARTED		='POSITION_GET_STARTED';
export const POSITION_GET_FINISHED		='POSITION_GET_FINISHED';
export const POSITION_GET_ERROR			='POSITION_GET_ERROR';

export const POSITION_WS_STARTED		='POSITION_WS_STARTED';
export const POSITION_WS_ERROR			='POSITION_WS_ERROR';
export const POSITION_WS_PARTIAL		='POSITION_WS_PARTIAL';
export const POSITION_WS_UPDATE			='POSITION_WS_UPDATE';
export const POSITION_WS_DELETE			='POSITION_WS_DELETE';
export const POSITION_WS_INSERT			='POSITION_WS_INSERT';

export const LEVERAGE_POST_STARTED		='LEVERAGE_POST_STARTED';
export const LEVERAGE_POST_FINISHED		='LEVERAGE_POST_FINISHED';
export const LEVERAGE_POST_ERROR		='LEVERAGE_POST_ERROR';

export const CLOSE_POSITION_STARTED		='CLOSE_POSITION_STARTED';
export const CLOSE_POSITION_FINISHED	='CLOSE_POSITION_FINISHED';
export const CLOSE_POSITION_ERROR		='CLOSE_POSITION_ERROR';