export const ORDER_BOOK_GET_STARTED		='ORDER_BOOK_GET_STARTED';
export const ORDER_BOOK_GET_FINISHED	='ORDER_BOOK_GET_FINISHED';
export const ORDER_BOOK_GET_ERROR		='ORDER_BOOK_GET_ERROR';

export const ORDER_BOOK_WS_STARTED		='ORDER_BOOK_WS_STARTED';
export const ORDER_BOOK_WS_PARTIAL		='ORDER_BOOK_WS_PARTIAL';
export const ORDER_BOOK_WS_UPDATE		='ORDER_BOOK_WS_UPDATE';
export const ORDER_BOOK_WS_DELETE		='ORDER_BOOK_WS_DELETE';
export const ORDER_BOOK_WS_INSERT		='ORDER_BOOK_WS_INSERT';