export const ASYNC_STORAGE_CRED='LIQUID_ASYNC_CRED';
export const KEYCHAIN_KEY='LIQUID_KEYCHAIN_KEY';
export const CURRENT_ACCOUNT='CURRENT_ACCOUNT';
export const ACCOUNTS_META='ACCOUNTS_META';
export const LIQUID_FIRST_TIME='LIQUID_FIRST_TIME';