export const RECENT_TRADES_GET_STARTED		='RECENT_TRADES_GET_STARTED';
export const RECENT_TRADES_GET_FINISHED		='RECENT_TRADES_GET_FINISHED';
export const RECENT_TRADES_GET_ERROR		='RECENT_TRADES_GET_ERROR';

export const RECENT_TRADES_WS_STARTED		='RECENT_TRADES_WS_STARTED';
export const RECENT_TRADES_WS_PARTIAL		='RECENT_TRADES_WS_PARTIAL';
export const RECENT_TRADES_WS_UPDATE		='RECENT_TRADES_WS_UPDATE';
export const RECENT_TRADES_WS_DELETE		='RECENT_TRADES_WS_DELETE';
export const RECENT_TRADES_WS_INSERT		='RECENT_TRADES_WS_INSERT';