export const CURRENT_PRICES_GET_STARTED	='CURRENT_PRICES_GET_STARTED';
export const CURRENT_PRICES_FINISHED	='CURRENT_PRICES_FINISHED';
export const CURRENT_PRICES_GET_ERROR	='CURRENT_PRICES_GET_ERROR';

export const PLACE_ORDER_POST_STARTED	='PLACE_ORDER_POST_STARTED';
export const PLACE_ORDER_POST_FINISHED	='PLACE_ORDER_POST_FINISHED';
export const PLACE_ORDER_POST_ERROR		='PLACE_ORDER_POST_ERROR';
