# fastlane/Fastfile
default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Testflight build"
  lane :testflight do
    match(type: "appstore", readonly: is_ci)
    gym(scheme: "bitmex-trading")
  end
end
