export const DEPOSIT_ADDRESS_GET_STARTED		='DEPOSIT_ADDRESS_GET_STARTED';
export const DEPOSIT_ADDRESS_GET_FINISHED		='DEPOSIT_ADDRESS_GET_FINISHED';
export const DEPOSIT_ADDRESS_GET_ERROR			='DEPOSIT_ADDRESS_GET_ERROR';
