export const MYORDERS_GET_STARTED	='MYORDERS_GET_STARTED';
export const MYORDERS_GET_FINISHED	='MYORDERS_GET_FINISHED';
export const MYORDERS_GET_ERROR		='MYORDERS_GET_ERROR';

export const MYORDERS_WS_STARTED	='MYORDERS_WS_STARTED';
export const MYORDERS_WS_ERROR		='MYORDERS_WS_ERROR';
export const MYORDERS_WS_PARTIAL	='MYORDERS_WS_PARTIAL';
export const MYORDERS_WS_UPDATE		='MYORDERS_WS_UPDATE';
export const MYORDERS_WS_DELETE		='MYORDERS_WS_DELETE';
export const MYORDERS_WS_INSERT		='MYORDERS_WS_INSERT';