export const TRADES_GET_STARTED					='TRADES_GET_STARTED';
export const TRADES_GET_FINISHED				='TRADES_GET_FINISHED';
export const TRADES_GET_ERROR					='TRADES_GET_ERROR';
export const TRADES_POSITION_GET_STARTED		='TRADES_POSITION_GET_STARTED';
export const TRADES_POSITION_GET_FINISHED		='TRADES_POSITION_GET_FINISHED';
export const TRADES_POSITION_GET_ERROR			='TRADES_POSITION_GET_ERROR';

export const TRADES_WS_STARTED				='TRADES_WS_STARTED';
export const TRADES_WS_PARTIAL				='TRADES_WS_PARTIAL';
export const TRADES_WS_UPDATE				='TRADES_WS_UPDATE';
export const TRADES_WS_DELETE				='TRADES_WS_DELETE';
export const TRADES_WS_INSERT				='TRADES_WS_INSERT';